add nav in header
js-tasks-ru/htmlcss-20210708_vladimir-vladimirovich-abramovich pull request #17
Opened 2021-08-27 08:33 UTC by Abramingys

2021-08-27 08:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-27 19:24 UTC, GSemikozov requested changes

2021-08-27 19:24 UTC, GSemikozov commented on components/header/header.css
> +    gap: 24px;
нам точно нужен такой гэп для одиночного элемента?)

2021-09-02 08:17 UTC, Abramingys commented on components/header/header.css
> +    gap: 24px;
задать для <p>отступ?

2022-02-25 13:18 UTC, closed without merging